title: Everyday Jobs
author: Everyday Jobs
avatar: https://everydayprojobs.com/assets/img/logo-black.png
email: jobs@morewithus.com
description: > # this means to ignore newlines until "twitter_username:"
   Find able and ready employees, helpers, and contractors for your 
   business (restaurant, gas station, store, salon, etc.) or home 
   (cleaning, babysitting, etc.).

# social links
twitter_username: jekyllrb
github_username:  jekyll
rss: rss
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com


show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html
header_pages:
  - title: Blog
    url: /
  - title: About Us
    url: https://everydayprojobs.com/info/about%20us
  - title: How it Works?
    url: https://everydayprojobs.com/info/how%20it%20works
  - title: Other Services
    url: https://everydayprojobs.com/info/other%20services
  - title: Login
    url: https://everydayprojobs.com/auth/login

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
